---
abstract: 'Perl extension for automated, regular backups'
author:
  - 'gualtiero chiaia'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1002, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-BackupPlan
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Tar: '1.76'
  DateTime: '0.78'
  File::Find: '1.15'
  Log::Log4perl: '1.33'
  XML::DOM: '1.44'
version: v0.0.8
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
